### ISSUE TITLE
Staff profile access levels

### ISSUE THREAD

**Issue by poseidonrisk** [FOSSBilling/FOSSBilling#1984] opened 2023-12-17 01:25 UTC
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like to be able to set permissions to each group. e.g. administrators, should have access to the entire site, while the support group should have access to certain areas of the site. As for people on the accounting team, they should have access to specific areas, too.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by BelleNottelling** [comment] 2023-12-17 02:11
Group-level permissions are a planned addition when we redo how the groups are implemented.
Closing as a duplicate of #1869

**Closed by BelleNottelling** 2023-12-17 02:11 UTC
Labels: feature request

**Comment by poseidonrisk** [comment] 2023-12-17 23:40
Sounds good. Please @ me, if you would, when this has been completed. Such a good feature to have on the admin level.

**Comment by BelleNottelling** [comment] 2023-12-19 22:50
> Sounds good. Please @ me, if you would, when this has been completed. Such a good feature to have on the admin level.

There is basically a zero percent chance I will remember to do that, but GitHub itself gives you two methods two receive a notification when progress is made.

You can subscribe that that issue and get notified when it's closed
![image](https://github.com/FOSSBilling/FOSSBilling/assets/17304943/1e675d34-4fcb-4f48-93d6-b54155ee987c)


Or you can watch the repository for releases and check the release notes for any mention of it being completed.
![image](https://github.com/FOSSBilling/FOSSBilling/assets/17304943/1c8154cd-24f1-45d2-8315-0a37bbcca307)
