### ISSUE TITLE
[Bug] Can't send tests mails while maintenance mode is enabled

### ISSUE THREAD

**Issue by guillaumearnx** [FOSSBilling/FOSSBilling#1374] opened 2023-06-26 13:16 UTC
### Describe the bug

When modifying the settings for sending emails, it is impossible to send a test email on the administrator interface if the maintenance mode is activated.

### How to reproduce

1. Go to the administrator interface
2. Click on system then settings
3. Go to Email then Email Settings
4. Click on "Send test email to staff members"

### Expected behavior

Send a test mail to staff members

### Screenshots

![image](https://github.com/FOSSBilling/FOSSBilling/assets/37373941/86e6edce-c413-4fdf-a3b4-f1713b2b94d8)

### FOSSBilling version

0.5.1

### Device

Desktop

### Information

- Device: Laptop
- OS: Windows 11
- Browser: Microsoft Edge

**Comment by guillaumearnx** [comment] 2023-06-28 14:05
The problem also occurs when trying to connect to a server (HestiaCP in my case) after clicking on the "Test connection to server" button.

**Comment by jaapmarcus** [comment] 2023-06-28 14:18
Check the error logs in /data/logs/ folder ..

**Comment by guillaumearnx** [comment] 2023-06-28 14:38
Sorry, i forgot to post them there, I've all posted on discord.

There is no more informations in logs.

![image](https://github.com/FOSSBilling/FOSSBilling/assets/37373941/9eac4330-5479-4730-8c6a-f2df2264fc75)

With debug mode :

![image](https://github.com/FOSSBilling/FOSSBilling/assets/37373941/2e232f4a-257e-4d1b-a918-0c741b056cde)

**Comment by jaapmarcus** [comment] 2023-06-28 15:09
So the maintenance mode disables the function

**Comment by guillaumearnx** [comment] 2023-06-28 16:17
Perfect example of "That's not a bug, that's a feature".

I don't think it's intended to disable test functions in maintenance mode.

But if so then no worries, I thought it was a bug

**Comment by jaapmarcus** [comment] 2023-06-28 16:24
> Perfect example of "That's not a bug, that's a feature".
> 
> I don't think it's intended to disable test functions in maintenance mode.
> 
> But if so then no worries, I thought it was a bug

It makes sense to do not send email when maintence mode Is enabled but it should probably not apply to test mails..

**Comment by evrifaessa** [comment] 2023-06-28 19:51
The error message rather seems like an actual error instead of an intended “feature”. I'd call this a bug.

**Comment by Anuril** [comment] 2023-07-30 00:28
Hi! This is not a bug. 

You need to enter "Allowed IPs" or 'allowed_urls' for the mainenance mode to allow you to do _anything_ that involves the API. When you set it up correctly, you're good to go.

```
array (
    'enabled' => true,
    'allowed_urls' =>
    array (
    ),
    'allowed_ips' =>
    array ( '10.12.34.56'
    ),
  ),
```
or if you're behind a reverse proxy:

```
array (
    'enabled' => true,
    'allowed_urls' =>
    array ( 'https://fossbilling.mydomain.com/admin'
    ),
    'allowed_ips' =>
    array (
    ),
  ),
```

This issue can imho be closed as #wontfix.

**Comment by BelleNottelling** [comment] 2023-07-30 00:43
> Hi! This is not a bug. 
> 
> You need to enter "allowed_ips" or "allowed_urls" for the mainenance mode to allow you to do _anything_ that involves the API. When you set it up correctly, you're good to go.
> 
> ```
> array (
>     'enabled' => true,
>     'allowed_urls' =>
>     array (
>     ),
>     'allowed_ips' =>
>     array ( '10.12.34.56'
>     ),
>   ),
> ```
> or if you're behind a reverse proxy:
> 
> ```
> array (
>     'enabled' => true,
>     'allowed_urls' =>
>     array ( 'https://fossbilling.mydomain.com/admin'
>     ),
>     'allowed_ips' =>
>     array (
>     ),
>   ),
> ```
> 
> This issue can imho be closed as #wontfix. 

No, you are still supposed to be able to perform actions as an administrator

**Closed** 2023-07-30 13:39 UTC
Labels: bug
