### ISSUE TITLE
[Bug] order services goes to 404 in when logged in

### ISSUE THREAD

**Issue by weismannweb** [FOSSBilling/FOSSBilling#306] opened 2022-09-30 11:24 UTC
**Describe the bug**
order services goes to 404

Page /orderbutton&theme_color=green&loader=1 not found.

**To Reproduce**
click on order services after login

**Expected behavior**
to see order services

**Screenshots**
https://watch.screencastify.com/v/8b0fSJa3QzFO4GYHZGSC

**Comment by BelleNottelling** [comment] 2022-10-22 22:52
I am unable to reproduce this issue. The select product screen displays without issue:
![image](https://user-images.githubusercontent.com/17304943/197365146-a619b353-ee40-4568-a25f-cdacc90f8d9d.png)

**Comment by BelleNottelling** [comment] 2022-10-28 01:29
Hey, @weismannweb 
Are you still experiencing this issue?

**Comment by BelleNottelling** [comment] 2022-12-01 19:46
Closing since I was unable to reproduce this, I suspect we fixed this in one of the many PRs we've merged since it was reported

**Closed by BelleNottelling** 2022-12-01 19:46 UTC
Labels: bug

**Comment by evrifaessa** [comment] 2022-12-01 19:48
My only thought is that it might be a server misconfiguration.

The `/orderbutton` path is a SEO-friendly path and SEF URLs won’t work until you properly configure the web server.

**Comment by evrifaessa** [comment] 2022-12-01 19:53
oh right. I haven’t checked the video, so…
