### ISSUE TITLE
[Feature Request] Extension auto update

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#1045] opened 2023-04-03 16:38 UTC
**Is your feature request related to a problem? Please describe.**
It's quite challenging trying to update an extension, in this case the Proxmox extension because you have to delete the folder to be able to install a new one.

**Describe the solution you'd like**
Ability to update without having to use the CLI to delete or over right the exiting folder

**Describe alternatives you've considered**

**Additional context**

**Comment by BelleNottelling** [comment] 2023-04-03 20:16
Duplicate of #983

**Closed by BelleNottelling** 2023-04-03 20:16 UTC
Labels: feature request
