### ISSUE TITLE
[Bug] Strings missing for translate from English to other langs

### ISSUE THREAD

**Issue by evilmc** [FOSSBilling/FOSSBilling#1990] opened 2023-12-18 01:10 UTC
### Describe the bug

I found a few strings for translation that I couldn't find on crowdin.com. So far, I've noticed a few, and if there are any left lately, add directions to where they are.

**This is for Serbian language.**

### How to reproduce

This strings are in backend.

### Expected behavior

1. This is in service details: Renewal date in 365 day(s) = **in 365 day(s)** missing for translate
2. This is in user Services invoices: Pending Setup = **Pending Setup** missing for translate
3. This is in user Services invoices: Manage = **Manage** missing for translate
4. This is in user Invoice: Invoice #IDnumber = **Invoice #IDnumber** missing for translate
5. This is in Admin backend: Order Management = **-- Select status --, Pending setup, Setup failed, Active, Suspended, Canceled** missing for translate
6. This is in Admin backend: Order Management - Order status history = **Order created, Order activated, Order could not be activated due to error: Only pending setup or failed orders can be activated** missing for translate
7. This is in Admin backend: Recent clients activity tab = **Checked out shopping cart** missing for translate
8. This is in Admin backend: Recent clients activity tab = **13 minutes ago** = 13 minutas pre (this is wrong translation) missing for translate
9. This is in Admin backend: Recent clients activity tab = **Approved invoice "22"** missing for translate
10. This is in Admin backend: Recent clients activity tab = **Prepared new invoice "22"** missing for translate
11. This is in Admin backend: Recent clients activity tab = **Added "DNS Start" to shopping cart** missing for translate
12. This is in Admin backend: Recent clients activity tab = **Checked out shopping cart** missing for translate
13. This is in Admin backend: Recent clients activity tab = **Removed product from shopping cart** missing for translate
14. This is in Admin backend: Recent clients activity tab = **Removed product addon from shopping cart** missing for translate
15. This is in Admin backend: Recent staff activity tab = **Marked invoice "21" as paid** missing for translate
16. This is in Admin backend: Recent staff activity tab = **Activated order #28** missing for translate
17. This is in Admin backend: Recent staff activity tab = **Updated invoice "21"** missing for translate
18. This is in Admin backend: Recent staff activity tab = **Updated payment gateway ClientBalance** missing for translate
19. This is in Admin backend: Recent staff activity tab = **Logged in as client #2** missing for translate
20. This is in Admin backend: Recent staff activity tab = **Updated FOSSBilling from 0.6.2 to 0.6.3** missing for translate
21. This is in Admin backend: Recent staff activity tab = **Updated system general settings** missing for translate
22. System Settings all strings: **Client, Scheduled Tasks, Currency, Email, Invoices, Orders, Staff, Support, System, Theme, Order Button, Form Builder, Redirect, Wysiwyg, Paid support module** missing for translate

### FOSSBilling version

0.6.3

### Device

Desktop

**Comment by evilmc** [comment] 2023-12-19 15:43
PDF invoice file also need translation for this strings:

Invoice number]: RH00020 - This is also bag number**]:**
Invoice date: 18.12.2023
Due date: 23.12.2023
Invoice status: Unpaid

Quantity & Price

**Comment by BelleNottelling** [comment] 2023-12-19 17:22
We already have a roadmapped item to fix and fix all untranslatable strings and I've gone ahead and added a comment linking to this there.
So we can keep things centralized, I'd appreciate it if you could add any more items you discover to #1681 via a comment. I'm going to close this as a duplicate of the larger issue.

> PDF invoice file also need translation for this strings:

I just need to sync the latest sources with Crowdin for the Invoice PDFs, which I'll do soon.

> This is in Admin backend: Order Management

It might be easier to give the URI to where the source translation is rather than trying to describe it, but what you've done so far still works fine if you prefer to do that. ( Example: `/admin/order/manage/9`).

> This is in Admin backend: Recent clients activity tab

There's also probably not any reason to list the activity strings as I don't believe a single one of those are translatable, which is known.

> System Settings all strings: Client, Scheduled Tasks, Currency, Email, Invoices, Orders, Staff, Support, System, Theme, Order Button, Form Builder, Redirect, Wysiwyg, Paid support module missing for translate

These are module names which are untranslatable, which is known.

Thanks!

**Closed by BelleNottelling** 2023-12-19 17:22 UTC
Labels: bug
