### ISSUE TITLE
[Bug] Unable to Save settings and forms

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#51] opened 2022-05-23 13:02 UTC
https://github.com/boxbilling/boxbilling/issues/1126

**Comment by John-S4** [comment] 2022-05-24 06:37
I've just tried to reproduce this bug on a couple of installs and I can't. 

Has anyone else experienced this, or is it possible that it has already been fixed in a later update or that it was caused by something very specific to the OPs installation?

**Comment by 0x6b-dev** [comment] 2022-05-24 14:04
Closing this off because it appears to be related to the user setup.

Thanks for your help John.

**Comment by 0x6b-dev** [comment] 2022-05-24 15:52
I have managed to reproduce this.

1. New installation
2. Run through setup wizard
3. I did NOT delete install.php and attempted to get to admin page
4. Errors out
5. A page refresh yields a "Page /install/install.php not found" error message, and I can't log in at all now (install borked)

**Comment by BelleNottelling** [comment] 2022-05-24 16:22
Did you try deleting the file and then reloading the page?

**Comment by John-S4** [comment] 2022-05-24 17:56
Interesting, I think I deleted install.php both times, just without thinking about it.

**Comment by BelleNottelling** [comment] 2022-10-22 22:41
> 

I don't think that's the same issue, tbh. For starters, the way you described it doesn't sound like their issue, and they said everything worked correctly for about 2.5 hours and then broke,... I suspect some kind of bug broke their system. One which was very possibly fixed since then. As such, I want to close this one out as a "can not reproduce"

Also, the installer is supposed to delete the install folder after installing & it tells the user to as well.

**Comment by John-S4** [comment] 2022-10-23 08:57
> As such, I want to close this one out as a "can not reproduce"

Agreed. 

The user is instructed to remove the install folder, if they don't do it then it is user error and not software error. 

We probably should check if the folder is being consistently automatically deleted though, and if not work out why and correct it.

**Comment by BelleNottelling** [comment] 2022-10-23 09:12
> We probably should check if the folder is being consistently automatically deleted though, and if not work out why and correct it. 

I know I personally have never seen it fail to delete it, and if it does, it should display an error message instructing the user to delete it themselves. It sounds like there may be some kind of issue with that portion of it, though so that might be worth checking

**Comment by jaapmarcus** [comment] 2022-10-23 09:21
If php is running under a different user that the file owner. For example: www-data and the user upload it as "user" it will always fail

**Comment by evrifaessa** [comment] 2022-10-23 10:05
I’ve seen it happening to me sometimes. Nearly all of them were issues with the folder permissions.

**Comment by BelleNottelling** [comment] 2023-04-07 04:35
I'm going to close this. Even if there was some kind of permission issue during the installation, the user should be presented with an error message and some instructions to resolve the issue. Plus that situation seems unrelated to the original issue, which nobody else has reported & seemed like a 1-off issue many months ago, well before the significant improvements we've made

**Closed by BelleNottelling** 2023-04-07 04:35 UTC
Labels: bug
