### ISSUE TITLE
[Bug] Free domain registration not working with hosting order

### ISSUE THREAD

**Issue by zohaib87** [FOSSBilling/FOSSBilling#631] opened 2022-12-27 12:11 UTC
**Describe the bug**
Even if free domain registration is active for hosting from admin panel, It does not work, It adds the domain amount to the hosting amount. 

**To Reproduce**
1. Add tld.
2. Add hosting and enable free domain.
3. Order from client area.
4. It doesn't provide free domain with hosting.

**Expected behavior**
Free domain with hosting order and normal paid domain if purchased separately.

**Comment by jaapmarcus** [comment] 2023-01-09 11:27
Issue is caused by our own new api wrapper similar as in https://github.com/FOSSBilling/FOSSBilling/issues/665

**Comment by jaapmarcus** [comment] 2023-01-12 06:47
Fixed with linked PR

**Closed by jaapmarcus** 2023-01-12 06:47 UTC
Labels: bug
