### ISSUE TITLE
Translation of the months and change the format

### ISSUE THREAD

**Issue by heberq1978** [FOSSBilling/FOSSBilling#841] opened 2023-02-18 20:24 UTC
### Describe the bug

I would like to know how do I translate the months and how can I also change the format that appears in the email, to the following pattern:  d/m/Y

Thank You
Heber Queiroz

### How to reproduce

E-mail template

### Expected behavior

In the email templates, the dates are appearing as full and I would like them to appear in the simplified format.
Ex: dd/mm/YY

### FOSSBilling version

0.3.0

**Comment by exp0logy** [comment] 2023-02-25 15:29
Are you referring to Invoice dates?

What do you mean Translate Months?

This also is not a bug.
Please Close.

**Comment by heberq1978** [comment] 2023-02-25 16:59
> Are you referring to Invoice dates?
> 
> What do you mean Translate Months?
> 
> This also is not a bug. Please Close.

My language is pt-br, and the months are getting  in english. Both in emails and on Fossbilling.
The date pattern is also in American format so I'm asking for help as the translation file is not translating the months into Portuguese.
I know it wouldn't be a bug, but there was no other way for me to get in touch.
If you can help me I would appreciate it, because each country has its own date and month writing format.

**Comment by BelleNottelling** [comment] 2023-02-25 17:12
Both the month and the time format can be changed inside the config.php file, and it uses the PHP datetime format, however I believe it only displays in English.
Here's the docs on the datetime format:
https://www.php.net/manual/en/datetime.format.php

Being able to translate the dates would be a feature request, not a bug, but it's a very valid request and shouldn't be closed.

**Comment by heberq1978** [comment] 2023-02-27 03:09
> Both the month and the time format can be changed inside the config.php file, and it uses the PHP datetime format, however I believe it only displays in English. Here's the docs on the datetime format: https://www.php.net/manual/en/datetime.format.php
> 
> Being able to translate the dates would be a feature request, not a bug, but it's a very valid request and shouldn't be closed.

Thank you very much, I was able to set the date as needed for me.

**Comment by admdly** [comment] 2023-03-26 19:52
Closing as resolved by #948.

**Closed by admdly** 2023-03-26 19:52 UTC
Labels: bug
