### ISSUE TITLE
[Bug] Some generated PDF  blocked by Chrome as Dangerous

### ISSUE THREAD

**Issue by mcl21us** [FOSSBilling/FOSSBilling#2005] opened 2023-12-23 15:02 UTC
### Describe the bug

Some PDF Generated invoices are blocked by Chrome blocked by the browser as DANGEROUS.

### How to reproduce

1. Invoice
2. Generate PDF
3. Redirect to PDF invoice but was tag as Dangerous

### Expected behavior

My observation this might be caused by the long URL pdf ID

### Screenshots

![image](https://github.com/FOSSBilling/FOSSBilling/assets/6890851/9736266e-1e8c-4dbc-a90c-1b3c20accc28)

### FOSSBilling version

0.6.4

### Device

Desktop, Smartphone

**Comment by BelleNottelling** [comment] 2023-12-24 02:01
I just tried 20 PDFs and had exactly zero issues.
I would suggest checking that the issue isn't your domain itself

**Comment by John-S4** [comment] 2024-01-11 10:35
I have also just tried this out a handful of times from three different domains and experienced no problems at all.

**Comment by BelleNottelling** [comment] 2024-01-12 22:28
I'm going to close this because we are unable to replicate it, nobody else has shared a similar experience, and you haven't responded in a few weeks.
If you're able to validate the issue is not with your domain itself we can look further into it, but for the time being this isn't reproducible and doesn't appear to be a FOSSBilling issue.

**Closed by BelleNottelling** 2024-01-12 22:28 UTC
