### ISSUE TITLE
[Feature Request] Keep Softaculous entry?

### ISSUE THREAD

**Issue by haydenwalker980** [FOSSBilling/FOSSBilling#460] opened 2022-11-15 04:57 UTC
Really just a question - when we go stable should we keep the Softaculous entry? I mean it would be easier, WAY easier to install if we did

**Comment by BelleNottelling** [comment] 2022-11-15 05:25
Duplicate of https://github.com/FOSSBilling/FOSSBilling/issues/60

**Closed by BelleNottelling** 2022-11-15 05:25 UTC
