### ISSUE TITLE
[Bug] Just restored, new version is full of bugs

### ISSUE THREAD

**Issue by isshiimwe** [FOSSBilling/FOSSBilling#701] opened 2023-01-14 23:50 UTC
After the update was done using automatic update via Extention, it just went buzz.

Can't register domain name!

**Comment by BelleNottelling** [comment] 2023-01-14 23:58
Can you please provide more information?
IE: what registrar are you using, what error are you getting? Where are you getting the error? (admin panel or client area), are there errors under /data/logs?

**Comment by isshiimwe** [comment] 2023-01-15 00:00
Getting Error in the Client area, can only access admin panel in incognito.

Tried clearing cashe & cookies but nothing was happen so i restored back to the previous version.

**Comment by BelleNottelling** [comment] 2023-01-15 00:03
If you could only access the admin panel in incognito, you didn't properly clear all of your browser's cache.

And, you only answered one of my questions, we still need to know what registrar you're using and what error you got when trying to register the domain. The more information you can provide with a bug report, the quicker we can narrow down what the issue is and get it resolved

**Comment by isshiimwe** [comment] 2023-01-15 00:06
I was getting this error

![image](https://user-images.githubusercontent.com/122705379/212502480-4bcaa010-9d8a-4f41-bf25-f6e61c373d4d.png)

**Comment by John-S4** [comment] 2023-01-15 00:10
There were definitely uncleared caches there (not necessarily the cause of the error) because that is using pre-uodate css

**Comment by isshiimwe** [comment] 2023-01-15 00:12
I don't think Cashes was the issue, maybe for Admin & client login but not for the order issue

**Comment by BelleNottelling** [comment] 2023-01-15 00:15
Cache was the login issue, the domain issue is separate and is fixed by the linked pull request.

**Closed** 2023-01-15 00:26 UTC
Labels: bug
