### ISSUE TITLE
[Feature Request] Some cart suggestions

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#1420] opened 2023-07-07 18:28 UTC
Continue shopping with option to checkout at any point when done adding all the products.

Cart button at the top of page to show empty or abandoned cart.

**Comment by BelleNottelling** [comment] 2023-07-08 08:37
Closing as a duplicate of #556 (It's not truly a duplicate, but these kinds of improvements should be done when the cart is rewritten as otherwise the work will just need to be done again)

**Closed by BelleNottelling** 2023-07-08 08:37 UTC
Labels: feature request
