### ISSUE TITLE
[Bug] Menu bar missing options in moblie view

### ISSUE THREAD

**Issue by epichosts** [FOSSBilling/FOSSBilling#1479] opened 2023-07-28 01:04 UTC
### Describe the bug

When viewing the billing panel from a mobile device (or a very small resolution), the menu disappears and just shows 'User Profile'.

### How to reproduce

Go to the main URL of the billing panel with a mobile device and you will not be able to see any of the menu selections.

### Expected behavior

To be able to see the menu in the same way as on computers so that the site can be navigated properly through mobile.

### Screenshots

Computer:
![screenshot-billing epichosts co uk-2023 07 28-02_03_49](https://github.com/FOSSBilling/FOSSBilling/assets/25933763/e418803d-406a-4f6b-b11c-a3f1a4cc07ae)

Mobile: 
![screenshot-billing epichosts co uk-2023 07 28-02_04_14](https://github.com/FOSSBilling/FOSSBilling/assets/25933763/3af425a6-aeca-4d1d-b7d2-83749725336a)

### FOSSBilling version

0.5.4

### Device

Smartphone

### Information

Any device with a tiny resolution

**Comment by BelleNottelling** [comment] 2023-07-28 08:48
Duplicate of #1370. Will be fixed in #1472 when Huraga is migrated to Bootstrap 5

**Closed by BelleNottelling** 2023-07-28 08:48 UTC
Labels: bug
