### ISSUE TITLE
[Bug] Error when I try to check for domain availability using ResellerClub

### ISSUE THREAD

**Issue by avaneeshk098** [FOSSBilling/FOSSBilling#1380] opened 2023-06-28 10:29 UTC
### Describe the bug

I am receiving the following error on trying to check if a domain is available:

```
HttpClientException: HTTP/2 500 returned for "https://httpapi.com/api/domains/available.json?domain-name=checkit&tlds=com&suggest-alternative=false&auth-userid=<AUTH_ID>&api-key=<API_KEY>". (9999)
```

However, sending the request through my local machine works fine. I had whitelisted my IP on the ResellerClub Admin portal.

### How to reproduce

1. Login into a client account
2. Click New Order
3. Order a Domain Register/Transfer
4. Enter any SLD and TLD
5. Click `check` to product the error above. 

### Expected behavior

I was hoping for it to return the status of the domain availability. 

However, one fix I thought might work is to add the IP through which the request is being sent to ResellerClub into the whitelist. This fixed it on my local machine, so I might fix it here as well. 

### FOSSBilling version

0.5.0

**Comment by BelleNottelling** [comment] 2023-06-28 17:17
Duplicate of #1267

**Closed by BelleNottelling** 2023-06-28 17:17 UTC
Labels: bug
