### ISSUE TITLE
[Bug] dark mode logo is white and light mode logo is black and unreadable

### ISSUE THREAD

**Issue by givinghawk** [FOSSBilling/FOSSBilling#336] opened 2022-10-11 17:57 UTC
**Describe the bug**
dark mode logo is white and light mode logo is black and unreadable

**To Reproduce**
1. turn on dark mode in admin area or not
2. look at the goofy ahh logo

**Expected behavior**
readable logo on light mode
coloured logo on dark mode

**Screenshots**
![image](https://user-images.githubusercontent.com/72263189/195165002-e209a1be-ad6e-4354-b275-180a4ff54444.png)
![image](https://user-images.githubusercontent.com/72263189/195165036-83a65504-79c2-4a46-8876-2d315c13a9c6.png)

**Desktop (please complete the following information):**
 - OS: windows 10 pro
 - Browser chrome 96 (idk)
 - Version ^

**Additional context**
thats all

**Comment by evrifaessa** [comment] 2022-10-11 18:05
Duplicate of #183.

**Closed by evrifaessa** 2022-10-11 18:05 UTC
Labels: bug
