### ISSUE TITLE
[Bug] HTTP Error 500 when trying to access

### ISSUE THREAD

**Issue by Ben569483** [FOSSBilling/FOSSBilling#1364] opened 2023-06-23 18:58 UTC
### Describe the bug

I can't access FOSSBilling, I am given a HTTP 500 error.

### How to reproduce

1. Go to the FOSSBilling site
2. Witness the 500 error

### Expected behavior

FOSSBilling to load or install.

### FOSSBilling version

latest stable

### Device

Desktop, Smartphone

### Additional context

using PHP 8.0.0

**Comment by BelleNottelling** [comment] 2023-06-23 19:09
I'm a bit confused here, is the issue with one of our sites or with an installation you have?

And if it's an installation you have, are you getting this on the installer or is it happening after an update?
If it's after an update, what version did you update from?

**Comment by Ben569483** [comment] 2023-06-23 19:10
This is with my installation, I am not able to access anything without it giving a 500 error.

**Comment by jaapmarcus** [comment] 2023-06-23 19:18
Check error logs...

**Comment by Ben569483** [comment] 2023-06-23 19:25
[Untitled-1.txt](https://github.com/FOSSBilling/FOSSBilling/files/11851576/Untitled-1.txt)
Here's error logs...

**Comment by BelleNottelling** [comment] 2023-06-24 17:31
The only error in that log suggest that the file owners / permissions of the `/home/billing/public_html/index.php` is incorrect (although most likely it's the entire directory and not just the `index.php` file).
https://www.inmotionhosting.com/support/server/ssh/uid-smaller-than-min-uid/

It's fairly typical for a control panel to provide a button that can be used to fix file permissions, that would be the easiest way to resolve the issue. Otherwise, you need to login the server and use the CLI to correct the permissions as described in the link I shared above.

**Comment by Ben569483** [comment] 2023-06-25 00:59
That worked, I got to proceed to the installer but when I put in my database info and hit next, it does nothing apart from severely lag my server. These below lines are the only errors I can see in my error log.

"End of script output before headers: install.php"
"SoftException in Application.cpp:350: UID of script "/home/billing/public_html/install/install.php" is smaller than min_uid

**Comment by BelleNottelling** [comment] 2023-06-25 01:40
> "End of script output before headers: install.php"
> "SoftException in Application.cpp:350: UID of script "/home/billing/public_html/install/install.php" is smaller than min_uid

These are still the same errors as before, make sure to apply the permission fix to the entire `/home/billing/public_html/` directory and apply them recursively

**Comment by Ben569483** [comment] 2023-06-25 11:21
i'm still unfortunately having the same issue, i have set file ownership properly but still the same issue

**Comment by Ben569483** [comment] 2023-06-25 11:39
[php_error.log](https://github.com/FOSSBilling/FOSSBilling/files/11859563/php_error.log)

**Comment by BelleNottelling** [comment] 2023-06-25 14:59
Okay, that error log indicates that PHP is running out of memory when it's trying to include the required packages, what's your PHP memory limit set at? You may need to increase it more

**Comment by Ben569483** [comment] 2023-06-25 15:05
seems like my php.ini says the max memory is 128mb; i forgot php had it's own memory limits, what would be the recommended amount?

**Comment by BelleNottelling** [comment] 2023-06-25 17:27
128mb should be sufficient.
Try restarting the server, re-downloading the latest FOSSBilling release, and then try it again.

If it doesn't work still, increase the memory limit to 256mb, but that shouldn't be needed

**Comment by Ben569483** [comment] 2023-06-25 17:46
i increased php memory to 512mb but no success, it seems to be overloading my cpu creating over 200 processes
![process counter, normally at around 50-60](https://github.com/FOSSBilling/FOSSBilling/assets/35010334/f601c7b3-714e-4ab2-9496-114047e4bf69)

**Comment by BelleNottelling** [comment] 2023-06-25 21:24
@Ben569483 
Try replacing the `/install/install.php` file with the one found here:
https://raw.githubusercontent.com/BelleNottelling/FOSSBilling/fix/remove-installer-https-redirect/src/install/install.php

**Comment by Ben569483** [comment] 2023-06-25 22:03
the lag is now gone but it still won't write to my database and all the info is correct

**Comment by BelleNottelling** [comment] 2023-06-28 06:36
Can you check the error log that's generated at `/install/php_error.log`?

**Comment by Ben569483** [comment] 2023-06-28 19:18
i don't see an error log in that directory, all that happens is clicking next causes php-fpm's cpu usage to go up slightly, but that's the only sign of anything i see happening, i've tried 2 different database logins, including my server's billing account username and also as root
![image](https://github.com/FOSSBilling/FOSSBilling/assets/35010334/1a4fdc20-e84f-40b1-917d-4ef065fbb8eb)

**Comment by Ben569483** [comment] 2023-07-08 17:43
same thing still happens, i tried naming the database different, different user account, different credentials, deleting and re-creating the entire user but no success, same issue occurs in BoxBilling, i manually updated to the latest version but same old same old

**Comment by BelleNottelling** [comment] 2023-07-09 03:31
Make sure you are going in and giving the user full control over the DB. That's the only suggestion I have.
Plenty of people have used FOSSBilling on CWP without issue, so the issue you are experiencing seems to be something specific to your environment

**Comment by BelleNottelling** [comment] 2023-08-10 06:53
Closing. This is over a month old, we can't reproduce the issue, and it is most likely a permissions issue or something specific to your installation.

**Closed by BelleNottelling** 2023-08-10 06:53 UTC
Labels: bug
