### ISSUE TITLE
[Bug] Currency change affects user access

### ISSUE THREAD

**Issue by joseluismktcuba** [FOSSBilling/FOSSBilling#495] opened 2022-12-01 17:17 UTC
**Describe the bug**

I accessed Settings/Currency-settings and added a new currency CUP Cuba Peso, set it to default and removed the USD.

Then the user who had made a previous purchase in usd gets an error message and also sometimes when accessing. The message reads: An exception has been thrown during the rendering of a template ("Currency not found").

Also when you are going to make a purchase, this message appears: Selected currency CUP does not match your profile currency USD. Please change cart currency to continue.

**Comment by BelleNottelling** [comment] 2022-12-04 00:25
> Then the user who had made a previous purchase in usd gets an error message and also sometimes when accessing. The message reads: An exception has been thrown during the rendering of a template ("Currency not found").

Yeah, with the way the system was built (over a decade ago), deleting a currency has a lot of complications. I'm not sure if there are any easy ways to fix it, though

**Comment by BelleNottelling** [comment] 2023-01-27 05:46
Closing this as a duplicate of https://github.com/FOSSBilling/FOSSBilling/issues/582 which has more information

**Closed by BelleNottelling** 2023-01-27 05:46 UTC
Labels: bug
