### ISSUE TITLE
[Bug] Product properties (like billing terms, and available addons) are not updated

### ISSUE THREAD

**Issue by bidikov** [FOSSBilling/FOSSBilling#654] opened 2023-01-02 12:46 UTC
**Describe the bug**
Updates to the billing of products and products addons are not wirten in DB.

**To Reproduce**
Edit product, add pricing per month.
Save. Bo back to products still shows free.
No error seen on any part.

Latest install fresh done yesterday...
PHP 8.0
Did a manual change in the DB to make product recurrent but still admin/customer part does not pickup the change.

https://prnt.sc/n_WznYU2gz6P
https://prnt.sc/QYvIg_G0ZKb8
https://prnt.sc/toj0hpMe9x2a

**Comment by evrifaessa** [comment] 2023-01-02 15:52
Can reproduce.

**Comment by evrifaessa** [comment] 2023-01-02 16:08
This seems like a new issue. It doesn't exist in older releases, v0.2.4 as an example.

**Comment by evrifaessa** [comment] 2023-01-02 16:23
Alright. The thing with this issue, and the majority of the similar issues is this:

The old method (jQuery's AJAX) used to post data as "form data". While doing this, some fields in the form were named as "pricing[once][price]".

This is what it looked like when we were sending form data:
![image](https://user-images.githubusercontent.com/35808275/210257041-e8057327-555c-4037-ab70-a4ce816c8d9b.png)

Now that we are using JavaScript's native fetch API and we're posting data as JSON, this doesn't work and needs to be an object inside the JSON instead. I hope our API backend can parse and use objects inside JSON. This also might need some changes to be done inside the templates.

And this is how it looks like to post data as JSON now:

![image](https://user-images.githubusercontent.com/35808275/210257087-449441bf-a937-4f42-9062-2cdcd6708775.png)

You should notice that we aren't using objects. We need to fix that

**Comment by evrifaessa** [comment] 2023-01-02 16:25
Just did some tests. When you put the pricing data inside an object like it should have been, it works pretty fine. This means the backend API might not need changes, and it should work fine once we update the wrapper and the affected templates.

![image](https://user-images.githubusercontent.com/35808275/210257430-1924546e-d1ed-4646-8fdf-c991a9ddfed2.png)

**Comment by BelleNottelling** [comment] 2023-01-03 06:44
Hello, @bidikov 
Please try using the changes in the linked PR to see if this resolves this issue for you and verify there aren't any issues introduced with it.

Thank you!

**Comment by bidikov** [comment] 2023-01-03 08:11
Hi,
I will try to pull the file which was changed manually so i can check the efects - the machine where this is hosted does not have the right tooling for development...

**Comment by bidikov** [comment] 2023-01-03 09:28
Hi,

i have updates the API.js file but still something is strange - expacialy since in the DB i have the entries for the product to be reccurent and the admin panel stll sees the product as FREE when i enter product edit page...

With thechanged file, modifications for the product prices  are still not saved (as i have seen into the DB also) ...

Not sure, but this looks like some API misscommuniation as i'm certain my direct changes in the DB (based on the screen shots above) are correct...

**Comment by evrifaessa** [comment] 2023-01-03 09:31
@bidikov If you want to test changes and modify the assets, you should regenerate the final JavaScript bundle by running `gulp` again. But if that’s a production build, the Gulpfile likely won’t exist.

Your best bet would be waiting until the change is merged, then upgrading to the latest preview build.

**Comment by BelleNottelling** [comment] 2023-01-03 16:52
> Hi,
> 
> i have updates the API.js file but still something is strange - expacialy since in the DB i have the entries for the product to be reccurent and the admin panel stll sees the product as FREE when i enter product edit page...
> 
> With thechanged file, modifications for the product prices are still not saved (as i have seen into the DB also) ...
> 
> Not sure, but this looks like some API misscommuniation as i'm certain my direct changes in the DB (based on the screen shots above) are correct...

Everything appears correct for me. I'd try setting it again from within the gui

**Comment by jaapmarcus** [comment] 2023-01-03 16:56
It might be a caching issue

**Closed** 2023-01-03 16:55 UTC
Labels: bug

**Comment by evrifaessa** [comment] 2023-01-03 16:59
You also have to run `gulp` manually.

**Comment by jaapmarcus** [comment] 2023-01-03 17:18
> You also have to run `gulp` manually.

No it is loaded separately 

https://github.com/FOSSBilling/FOSSBilling/pull/657/commits/5e1fc17e7598240015e05db8cff31c80b131d3ee#diff-4c7d24b8afe70316cb56030f39f6b03b2bff62e89f067b5f1b23c88386cfb7deR21
