### ISSUE TITLE
[Feature Request]Translation into Japanese

### ISSUE THREAD

**Issue by PYU224** [FOSSBilling/FOSSBilling#2251] opened 2024-04-22 07:29 UTC
**Is your feature request related to a problem? Please describe.**
Hello.
I want to use this tool, but I think that Japanese user feel unuseful by English.
Would you transrate it into Japanese?

**Comment by BelleNottelling** [comment] 2024-04-22 16:49
Duplicate of #2252

**Closed by BelleNottelling** 2024-04-22 16:49 UTC
Labels: feature request
