### ISSUE TITLE
[Bug] Do the email templates on the admin area replace the templates in the modules/files

### ISSUE THREAD

**Issue by ifedan-ed** [FOSSBilling/FOSSBilling#1013] opened 2023-03-28 21:44 UTC
### Describe the bug

After modifying and enabling the templates in the admin area and being able to preview them. They don't seem to be used for sending mails as I have tested with the test mail mod

### How to reproduce

Modify and enable a template in the email settings section of admin area

### Expected behavior

The template should be used for sending future emails

### FOSSBilling version

latest stable

**Comment by BelleNottelling** [comment] 2023-04-01 07:51
Closing as duplicate of #1016, since both seem to be you needing some assistance with the email templates.

**Closed by BelleNottelling** 2023-04-01 07:51 UTC
Labels: bug
