### ISSUE TITLE
[Bug] Can't edit a product when maintenance mode is enabled

### ISSUE THREAD

**Issue by guillaumearnx** [FOSSBilling/FOSSBilling#1533] opened 2023-08-13 17:05 UTC
### Describe the bug

When modifying the settings of a product, it is impossible to save the changes if the maintenance mode is activated.

### How to reproduce

1. Go to the administrator interface
2. Click on **Product** then **Products and Services**
3. Select a product
4. Click on "Save"

### Expected behavior

Save the product configuration

### Screenshots

![image](https://github.com/FOSSBilling/FOSSBilling/assets/37373941/07ee8abc-4f80-42cb-91d5-562f88634488)

### FOSSBilling version

0.5.5

### Device

Desktop

### Information

- Device: Laptop
- OS: Windows 11
- Browser: Microsoft Edge

**Comment by BelleNottelling** [comment] 2023-08-14 02:01
Duplicate of #1374 which has been fixed in our dev branch, The next version of FOSSBilling will include this fix

**Closed by BelleNottelling** 2023-08-14 02:01 UTC
Labels: bug
