### ISSUE TITLE
[Bug] DB name can't contain hyphen (-)

### ISSUE THREAD

**Issue by phonkala** [FOSSBilling/FOSSBilling#189] opened 2022-07-25 12:31 UTC
**Describe the bug**
Was wondering why installer is not being able to connect to database at all, not with the preview version nor just by getting the source with git clone. The problem is, if there is a hyphen in database name, installer won't go past it and can't connect. Did not test any other characters. Hyphen in db username does not seem to cause issues.

**To Reproduce**
1. Create DB with hyphen (-) in it's name
2. Try to install

**Comment by chippytech** [comment] 2022-07-25 17:39
I tried fossb-install

**Comment by John-S4** [comment] 2022-07-25 20:16
It's a known issue that needs to be fixed and should have been documented. 

Just created a PR that makes a note about it on the installer page, so that at least people are aware of what the issue is. 

A proper fix should be created in the near future though.

**Comment by jaapmarcus** [comment] 2022-07-25 21:01
`2022/07/25 21:00:29 [error] 654757#654757: *3883 FastCGI sent in stderr: "PHP message: SQLSTATE[HY000]: General error: 1007 Can't create database 'box_test-db'; database existsPHP message: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-db' at line 1" while reading response header from upstream, client: 84.82.33.184, server: xxxx, request: "POST /install/install.php?a=check-db HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm-xxxx:", host: "xxxx", referrer: "http://xxxxx/install/install.php"`

**Comment by evrifaessa** [comment] 2022-07-26 07:35
Fixed with #191.

**Closed** 2022-07-26 07:35 UTC
Labels: bug
