### ISSUE TITLE
[Bug] support ticket counter incorrect or not reflecting what it says

### ISSUE THREAD

**Issue by jleiss** [FOSSBilling/FOSSBilling#1351] opened 2023-06-20 04:53 UTC
### Describe the bug

My dashboard says there are 8 tickets opened waiting for staff review but when I click on it nothing comes up.

### How to reproduce

click on tickets and click on tickets waiting for staff reply.

### Expected behavior

I would expect it to list the tickets waiting for staff response.

### Screenshots

<img width="1136" alt="image" src="https://github.com/FOSSBilling/FOSSBilling/assets/2677329/207a2001-4c3a-4827-846a-97af49641abb">

### FOSSBilling version

5.0

### Device

Desktop

**Comment by John-S4** [comment] 2023-06-21 06:08
I've also failed to reproduce this issue, so if it recurring after a cache clear then we will need some more info about the setup to try and find it.

**Comment by John-S4** [comment] 2023-07-12 07:19
Since there is no update from @jleiss and it doesn't seem to be reproducible, I'm gong to assume that this was a caching issue, and close this issue.

**Comment by John-S4** [comment] 2023-07-12 07:20
Since there is no update from @jleiss and it doesn't seem to be reproducible, I'm gong to assume that this was a caching issue, and close this issue.

**Closed by John-S4** 2023-07-12 07:20 UTC
Labels: bug
